name: Go

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Zip the application files
      run: Compress-Archive .\* app.zip

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chirags'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cc07cb5e05d94de0883b05e02dd226b7 }}
        package: '.\app.zip'
